openapi: 3.0.0
info:
  title: Payment
  version: '1.0'
  description: |
    These are the API for the (version =?)
    This API is a standard REST-style API that accepts /returns JSON requests and is located at :
    http://payment.walliitools.com/
  contact:
    name: Farah
    email: farahafrinhimu@gmail.com
    url: 'http://payment.walliitools.com'
  termsOfService: 'http://payment.walliitools.com/Home'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'http://payment.walliitools.com/Payment/'
    description: prod
paths: {}
components:
  schemas: {}
  securitySchemes:
    MerchantToken:
      name: MerchantToken
      type: apiKey
      in: query
    ApplicationToken:
      name: ApplicationToken
      type: apiKey
      in: query
